#####################
## SERVICIO MYSQL  ##
#####################
apiVersion: v1
kind: Service
metadata:
  name: mysql-id # Cambiar por SQL
  labels:
    id: "1000" # Cambiar por SQL
    app: mediawiki
    cliente: elcliente # Cambiar por SQL # Cambiar por SQL
spec:
  ports:
    - port: 3306
  selector:
    app: mediawiki
    tier: mysql
  clusterIP: None
---
########################
## DEPLOYMENT  MYSQL  ##
########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-id # Cambiar por SQL
  labels:
    id: "1000" # Cambiar por SQL
    app: mediawiki
    cliente: elcliente # Cambiar por SQL
spec:
  selector:
    matchLabels:
      id: "1000" # Cambiar por SQL
      app: mediawiki
      cliente: elcliente # Cambiar por SQL
      tier: mysql
  #replicas: 2 # Por defecto 2 Replicas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        id: "1000" # Cambiar por SQL
        app: mediawiki
        cliente: elcliente # Cambiar por SQL
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-id # Cambiar por SQL
        env:
        - name: MYSQL_DATABASE
          value: dbmiwiki # cambiar respecto al fichero de PVC y Cambiar por SQL
        - name: MYSQL_USER
          value: usuario # cambiar respecto al fichero de PVC y Cambiar por SQL
        - name: MYSQL_PASSWORD
          value: Coria21 # cambiar respecto al fichero de PVC y Cambiar por SQL
        - name: MYSQL_ROOT_PASSWORD
          value: Coria21 # cambiar respecto al fichero de PVC y Cambiar por SQL
        ports:
        - containerPort: 3306
          name: mysql-id # Cambiar por SQL
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-elcliente-mysql-id # cambiar respecto al fichero de PVC y Cambiar por SQL
