######################
## CLAIM PARA MYSQL ##
######################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elcliente-mysql-id
  labels:
    id: "1000" # Cambiar por SQL
    app: wordpress
    cliente: elcliente #CAMBIAR
spec:
  storageClassName: mysql-id # Cambiar por SQL
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
