###########################
## CLAIM PARA  Joomla   ##
###########################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elcliente-joomla-id # cambio
  labels:
    id: "1000" # Cambiar por SQL
    app: joomla
    cliente: elcliente #CAMBIAR
spec:
  storageClassName: joomla-id # Cambiar por SQL
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
