#############################
## Servicio de PrestaShop  ##
#############################
apiVersion: v1
kind: Service
metadata:
  name: prestashop-id #Cambiar por SQL
  labels:
    id: "1000" # Cambiar por SQL
    app: prestashop
    cliente: elcliente  # Cambiar por SQL
spec:
  ports:
    - port: 80
  selector:
    app: prestashop
    cliente: elcliente # Cambiar por SQL
    tier: frontend
  type: NodePort
---
###############################
## Deployment de PrestaShop  ##
###############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop-id #Cambiar por SQL
  labels:
    id: "1000" # Cambiar por SQL
    app: prestashop
    cliente: elcliente # Cambiar por SQL
spec:
  selector:
    matchLabels:
      id: "1000" # Cambiar por SQL
      app: prestashop
      cliente: elcliente # Cambiar por SQL
      tier: frontend
  # replicas: 4 # No sincronizacion con la B.D
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        id: "1000" # Cambiar por SQL
        app: prestashop
        cliente: elcliente # Cambiar por SQL
        tier: frontend
    spec:
      containers:
      - image: prestashop/prestashop:1.7.7.2-apache # Version de apache propietario PrestaShop
        name: prestashop-id #Cambiar por SQL
        env:
        - name: DB_SERVER
          value: mysql-id #CAMBIAR  POR EL SQL
        - name: DB_PASSWORD
          value: contrasena # CAMBIAR POR OA
        - name: DB_PREFIX
          value: ps_ 
        - name: DB_NAME
          value: prestashop
        - name: PS_FOLDER_ADMIN
          value: admin-id
        ports:
        - containerPort: 80
          name: prestashop-id #Cambiar por SQL
        volumeMounts:
        - name: prestashop-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: prestashop-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-elcliente-prestashop-id # Cambiar por SQL