#######################
## PV para drupal    ##
#######################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elcliente-drupal-id # Cambiar por SQL
  labels:
    id: "1000" # Cambiar por SQL
    app: drupal
    cliente: elcliente # Cambiar por SQL
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: drupal-id # Cambiar por SQL
  hostPath:
    path: /home/drupal-id # Cambiar por SQL