###########################
## Claim de  Prestashop ##
###########################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elcliente-prestashop-id # cambio
  labels:
    id: "1000" # Cambiar por SQL
    app: prestashop
    cliente: elcliente #Cambiar por SQL
spec:
  storageClassName: prestashop-id # Cambiar por SQL
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
